##THIS WILL BE COMPLETE AFTER ALPHA AND BETA STAGES AND WORKED ON CONCURRENTLY##
##ONCE ALPHA, BETA, AND MAINNET RELEASE ARE DONE, THERE WILL BE A FULL SCRIPT TO ENSURE PROPER SEAMLESS FUNCTIONALITY CALLED [S_TMN_Setup.py] THIS WILL BE FOR THE USER AND OPERATOR TO USE CONCURRENTLY##
